# Generated by Django 4.2.3 on 2023-07-18 19:10

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import panorbitapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False, validators=[panorbitapp.validators.CustomValidations.validate_name])),
                ('first_name', models.CharField(error_messages=' first name cannot be null', max_length=50, validators=[panorbitapp.validators.CustomValidations.validate_name])),
                ('last_name', models.CharField(error_messages=' last name cannot be null', max_length=50, validators=[panorbitapp.validators.CustomValidations.validate_name])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'TransGender'), ('N', 'NotToDisclose')], default='N', max_length=1)),
                ('mob_no', models.BigIntegerField(validators=[panorbitapp.validators.CustomValidations.validate_mobile_number])),
                ('email_verified', models.BooleanField(default=False)),
                ('mob_verified', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'custom_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=52)),
                ('continent', models.CharField(choices=[('Asia', 'ASIA'), ('Europe', 'EUROPE'), ('North America', 'NORTH_AMERICA'), ('Africa', 'AFRICA'), ('Oceania', 'OCENIA'), ('Antartica', 'ANTARTICA'), ('South America', 'SOUTH_AMERICA')], default='Asia', max_length=15)),
                ('region', models.CharField(blank=True, max_length=26, null=True)),
                ('surface_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('indep_year', models.SmallIntegerField(null=True)),
                ('population', models.IntegerField(default=0)),
                ('life_expectancy', models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True)),
                ('gnp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gnp_old', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('local_name', models.CharField(blank=True, max_length=45)),
                ('government_form', models.CharField(blank=True, max_length=45)),
                ('head_of_state', models.CharField(max_length=60, null=True)),
                ('capital', models.IntegerField(null=True)),
                ('code_2', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=35)),
                ('district', models.CharField(blank=True, max_length=20)),
                ('population', models.IntegerField(default=0)),
                ('country_code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='panorbitapp.country')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('user_otp_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_for', models.CharField(choices=[('email', 'Email'), ('mobile', 'Mobile')], max_length=6)),
                ('otp', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usr_otp',
                'unique_together': {('request_for', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=30)),
                ('is_official', models.BooleanField(default=False)),
                ('percentage', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('country_code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='language', to='panorbitapp.country')),
            ],
            options={
                'db_table': 'country_language',
                'managed': True,
                'unique_together': {('country_code', 'language')},
            },
        ),
    ]
